export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POSTS = 'POST/FETCH_POSTS';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/SHOW_ALERT';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const CHANGE_THEME = 'APP/CHANGE_THEME';

export const FETCH_SUGGESTIONS = 'AUTOCOMPLETE/FETCH_SUGGESTIONS';
export const SHOW_SUGGESTIONS = 'AUTOCOMPLETE/SHOW_SUGGESTIONS';
export const HIDE_SUGGESTIONS = 'AUTOCOMPLETE/HIDE_SUGGESTIONS';
export const SELECT_SUGGESTION = 'AUTOCOMPLETE/SELECT_SUGGESTION';
export const RESET_AUTOCOMPLETE = 'AUTOCOMPLETE/RESET_AUTOCOMPLETE';
